### ISSUE TITLE
Request: fix pypi metadata so that the README info is shown on the pypi page

### ISSUE THREAD

**Issue by DeflateAwning** [ipv6freely/tcpping#1]
I stumbled across the [pypi page for this project](https://pypi.org/project/tcpping/), but the README doesn't show there. Can you please fix the metadata on this project to fix that?

**Comment by ipv6freely** [comment]
Maybe in the future but not now.

**Comment by DeflateAwning** [comment]
Can you please re-open the issue until it gets done at some point in the future then? Otherwise, consider archiving this repo if you're defining it as "not maintained" with no plans for future maintenance.

**Comment by ipv6freely** [comment]
No sorry.

**Comment by DeflateAwning** [comment]
Why?
