### ISSUE TITLE
Request: add a CLI version, callable via `python3 -m tcpping <host>:<port>`

### ISSUE THREAD

**Issue by DeflateAwning** [ipv6freely/tcpping#2]
This library is awesome! It would be so great if there was a CLI version that was callable like `python3 -m tcpping <host>:<port>`.

Lots of prominent Python libraries support this sort or use, when a basic CLI tool can be envoked from the core functionality of the library.

**Comment by ipv6freely** [comment]
No, sorry. Feel free to fork it or submit a PR!

**Comment by DeflateAwning** [comment]
Okay, I'll do that! Can you please re-open the issue until it's complete so that I can track the effort?
